"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega .env na raiz do projeto (opcional; em produção use variáveis do sistema / systemd).
_env_path = BASE_DIR / '.env'
if _env_path.is_file():
    try:
        from dotenv import load_dotenv

        load_dotenv(_env_path)
    except ImportError:
        pass


def _env_bool(key: str, default: bool = False) -> bool:
    v = os.environ.get(key)
    if v is None:
        return default
    return v.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(key: str) -> list[str]:
    raw = os.environ.get(key, '')
    if not raw.strip():
        return []
    return [x.strip() for x in raw.split(',') if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Produção: DJANGO_DEBUG=False (ou omita DJANGO_DEBUG e defina só no servidor com False)
DEBUG = _env_bool('DJANGO_DEBUG', True)

_DEV_SECRET_FALLBACK = 'django-insecure-kg%wty1^bf7buth4ec#rfbo50#!fo=o8a(7^rkbqc2um76ld+b'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_FALLBACK)

if not DEBUG:
    if not SECRET_KEY or SECRET_KEY == _DEV_SECRET_FALLBACK or SECRET_KEY.startswith(
        'django-insecure-'
    ):
        raise ImproperlyConfigured(
            'Em produção defina DJANGO_SECRET_KEY no ambiente com um valor aleatório forte '
            '(não use SECRET_KEY de desenvolvimento).'
        )

_default_allowed = ['localhost', '127.0.0.1', '.localhost']
_env_hosts = _env_list('DJANGO_ALLOWED_HOSTS')
ALLOWED_HOSTS = _env_hosts if _env_hosts else list(_default_allowed)

if not DEBUG and set(ALLOWED_HOSTS) <= {'localhost', '127.0.0.1', '.localhost'}:
    raise ImproperlyConfigured(
        'Em produção defina DJANGO_ALLOWED_HOSTS com o domínio e/ou IP público do servidor '
        '(lista separada por vírgulas).'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'financeiro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DisableCSRFForAPI',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Garante que o Django procura a pasta static dentro dos teus apps
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# CORS / CSRF: origens locais + URLs públicas via ambiente (produção HTTPS)
_DEV_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
_extra_cors = _env_list('DJANGO_CORS_ALLOWED_ORIGINS')
_extra_csrf = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Preserva ordem e remove duplicatas
_seen: set[str] = set()
CORS_ALLOWED_ORIGINS = []
for o in _DEV_ORIGINS + _extra_cors:
    if o not in _seen:
        _seen.add(o)
        CORS_ALLOWED_ORIGINS.append(o)

_seen_csrf: set[str] = set()
CSRF_TRUSTED_ORIGINS = []
for o in _DEV_ORIGINS + _extra_csrf:
    if o not in _seen_csrf:
        _seen_csrf.add(o)
        CSRF_TRUSTED_ORIGINS.append(o)

# Em produção com frontend noutro domínio/porta, preencha DJANGO_CORS_ALLOWED_ORIGINS e
# DJANGO_CSRF_TRUSTED_ORIGINS (HTTPS). Same-origin (app + API no mesmo host) pode omitir.

# CORS: para login por sessão (cookie) é preciso credentials + origens explícitas
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
# Não definir Domain para o cookie ficar "host-only": assim é enviado no mesmo host (ex.: localhost:5173). Evita falha quando se usa 127.0.0.1 vs localhost.
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_AGE = 86400 * 2
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

# Atrás de Nginx (ou outro proxy) terminando TLS
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# API REST: autenticação por Token (header Authorization: Token <key>). Sem cookies/sessão.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
}
