# Generated by Django 6.0.2 on 2026-02-28 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='produto_pai',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='variacao',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamentofornecedor',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco_unitario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.PositiveIntegerField(default=0)),
                ('fornecedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_no_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='financeiro.fornecedor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.material')),
            ],
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
