# Generated by Django 6.0.2 on 2026-03-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_categoriaproduto_produto_categoria_alter_itemvenda_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'ordering': ['tipo', 'nome']},
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Categoria de Produto'), ('material', 'Categoria de Material')], default='produto', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaproduto',
            unique_together={('nome', 'tipo')},
        ),
    ]
