# Generated by Django 6.0.2 on 2026-03-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'material'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='financeiro.categoriaproduto'),
        ),
    ]
