# Generated by Django 6.0.2 on 2026-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_material_categoria'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='fornecedor',
                    name='cpf',
                    field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
                ),
                migrations.AddField(
                    model_name='fornecedor',
                    name='cnpj',
                    field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
                ),
            ],
            database_operations=[],
        ),
    ]
