# Generated by Django 6.0.2 on 2026-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_perfilusuario_role_1_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de referência'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço (legado)'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de referência'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço (legado)'),
        ),
    ]
