# Generated by Django 6.0.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_ativo_cancelada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoClienteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_produtos', to='financeiro.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_por_cliente', to='financeiro.produto')),
            ],
            options={
                'verbose_name': 'Preço cliente × produto',
                'verbose_name_plural': 'Preços cliente × produto',
            },
        ),
        migrations.AddConstraint(
            model_name='precoclienteproduto',
            constraint=models.UniqueConstraint(fields=('cliente', 'produto'), name='financeiro_precoclienteproduto_unique_cliente_produto'),
        ),
    ]
