# Generated by Django 6.0.2 on 2026-03-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_ordem_compra'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='precoclienteproduto',
            name='financeiro_precoclienteproduto_unique_cliente_produto',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(default='Pix', max_length=50),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagamentofornecedor',
            name='observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='precoclienteproduto',
            unique_together={('cliente', 'produto')},
        ),
    ]
