# Generated by Django 6.0.2 on 2026-03-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_add_metodo_observacao_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_cliente', to='financeiro.contabanco'),
        ),
        migrations.AddField(
            model_name='pagamentofornecedor',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_fornecedor', to='financeiro.contabanco'),
        ),
    ]
