# Generated by Django 6.0.2 on 2026-03-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_add_conta_to_pagamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteEstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_estoque', to='financeiro.produto')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
