# Generated by Django 6.0.2 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0022_funcionarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="revenda",
            field=models.BooleanField(default=False, verbose_name="Revenda"),
        ),
        migrations.AddField(
            model_name="produto",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="financeiro.fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="produto",
            name="margem_lucro_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]

