# Generated by Django 6.0.2 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0023_produto_revenda_campos"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraProduto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_no_dia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras_produtos",
                        to="financeiro.fornecedor",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_produtos",
                        to="financeiro.ordemcompra",
                    ),
                ),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="financeiro.produto")),
            ],
        ),
    ]

