# Generated by Django 6.0.2 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0024_compraproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="fabricado",
            field=models.BooleanField(default=False, verbose_name="Fabricado"),
        ),
        migrations.AddField(
            model_name="produto",
            name="mao_obra_unitaria",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="ProdutoInsumo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="financeiro.material")),
                (
                    "produto",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="insumos", to="financeiro.produto"),
                ),
            ],
            options={
                "unique_together": {("produto", "material")},
            },
        ),
    ]

