# Generated by Django 6.0.3 on 2026-03-29 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_compra_data_compra_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramaterial',
            name='data_lancamento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de lançamento'),
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='data_lancamento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de lançamento'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='data_lancamento',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Momento em que a ordem foi registrada no sistema.', verbose_name='Data de lançamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_lancamento',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Momento em que a venda foi registrada no sistema (não altera com a data da venda).', verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='compramaterial',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data da operação de compra (pode ser ajustada após salvar).', verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data da operação de venda (pode ser ajustada após salvar).', verbose_name='Data da venda'),
        ),
    ]
