# Generated by Django 6.0.3 on 2026-03-31 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0030_ordemcompra_cancelada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='RegistroImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('compra', 'Compra'), ('fechamento_cliente', 'Fechamento cliente'), ('fechamento_cliente_selecao', 'Fechamento cliente (seleção)'), ('fechamento_fornecedor', 'Fechamento fornecedor'), ('fechamento_fornecedor_selecao', 'Fechamento fornecedor (seleção)')], max_length=48)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
