# Generated by Django 6.0.3 on 2026-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0037_ordemcompra_ultima_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramaterial',
            name='marcada_paga',
            field=models.BooleanField(default=False, help_text='Só para linha sem ordem; com ordem, usa a marcação da ordem.', verbose_name='Marcada como paga (avulsa)'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='marcada_paga',
            field=models.BooleanField(default=False, help_text='Só para linha sem ordem; com ordem, usa a marcação da ordem.', verbose_name='Marcada como paga (avulsa)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preco_fabricacao',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Opcional: preço usado só no custo de insumos. Compras e estoque usam preco_unitario_base.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='marcada_paga',
            field=models.BooleanField(default=False, help_text='Controle manual no detalhe do cliente; não substitui pagamentos lançados.', verbose_name='Marcada como paga'),
        ),
    ]
