# Generated by Django 6.0.3 on 2026-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0039_precificacao_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramaterial',
            name='preco_no_dia',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='preco_no_dia',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='precoclienteproduto',
            name='preco',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
    ]
