# Generated by Django 6.0.3 on 2026-07-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0041_ordemcompra_numero_venda_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('partner_id', models.CharField(blank=True, default='', max_length=64)),
                ('partner_key', models.CharField(blank=True, default='', max_length=256)),
                ('shop_id', models.CharField(blank=True, default='', max_length=64)),
                ('redirect_url', models.CharField(blank=True, default='', max_length=500)),
                ('conectado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loja Shopee',
                'verbose_name_plural': 'Lojas Shopee',
                'ordering': ['nome', 'id'],
            },
        ),
    ]
