# Generated by Django 6.0.3 on 2026-07-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0042_shopee_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contabanco',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='material',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='financeiro.material'),
        ),
        migrations.AlterField(
            model_name='ajusteestoqueproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_estoque', to='financeiro.produto'),
        ),
        migrations.AlterField(
            model_name='compramaterial',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='financeiro.fornecedor'),
        ),
        migrations.AlterField(
            model_name='compramaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.material'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_produtos', to='financeiro.fornecedor'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.produto'),
        ),
        migrations.AlterField(
            model_name='movimentobanco',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contabanco'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra', to='financeiro.fornecedor'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.cliente'),
        ),
        migrations.AlterField(
            model_name='pagamentofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_feitos', to='financeiro.fornecedor'),
        ),
        migrations.AlterField(
            model_name='precoclienteproduto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos_produtos', to='financeiro.cliente'),
        ),
        migrations.AlterField(
            model_name='precoclienteproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos_por_cliente', to='financeiro.produto'),
        ),
        migrations.AlterField(
            model_name='produtoinsumo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.material'),
        ),
        migrations.AlterField(
            model_name='produtoinsumo',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='financeiro.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='financeiro.cliente'),
        ),
    ]
