# Generated by Django 6.0.3 on 2026-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0043_proteger_historico_cadastros'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopeeloja',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shopeeloja',
            name='ambiente',
            field=models.CharField(choices=[('sandbox', 'Sandbox (teste)'), ('producao', 'Produção')], default='sandbox', max_length=16, verbose_name='Ambiente Open Platform'),
        ),
        migrations.AddField(
            model_name='shopeeloja',
            name='merchant_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shopeeloja',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shopeeloja',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
