# Generated by Django 6.0.3 on 2026-07-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0044_shopee_oauth_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopeeloja',
            name='ambiente',
            field=models.CharField(choices=[('sandbox', 'Sandbox (teste)'), ('producao', 'Produção')], default='producao', max_length=16, verbose_name='Ambiente Open Platform'),
        ),
    ]
