"""
URLs da API REST para o frontend React.
"""
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views_api
from . import views_auth

urlpatterns = [
    path('auth/login/', csrf_exempt(views_auth.AuthLogin.as_view())),
    path('auth/logout/', csrf_exempt(views_auth.AuthLogout.as_view())),
    path('auth/me/', views_auth.AuthMe.as_view()),
    path('usuarios/', views_auth.UsuarioListCreate.as_view()),
    path('usuarios/<int:pk>/', views_auth.UsuarioDetail.as_view()),
    path('clientes/', views_api.ClienteListCreate.as_view()),
    path('clientes/<int:pk>/', views_api.ClienteDetail.as_view()),
    path('fornecedores/', views_api.FornecedorListCreate.as_view()),
    path('fornecedores/<int:pk>/', views_api.FornecedorDetail.as_view()),
    path('produtos/', views_api.ProdutoListCreate.as_view()),
    path('produtos/<int:pk>/', views_api.ProdutoDetail.as_view()),
    path('materiais/', views_api.MaterialListCreate.as_view()),
    path('materiais/<int:pk>/', views_api.MaterialDetail.as_view()),
    path('categorias/', views_api.CategoriaListCreate.as_view()),
    path('categorias/<int:pk>/', views_api.CategoriaDetail.as_view()),
    path('contas/', views_api.ContaListCreate.as_view()),
    path('contas/<int:pk>/', views_api.ContaDetail.as_view()),
    path('vendas/', views_api.VendaListCreate.as_view()),
    path('vendas/<int:pk>/', views_api.VendaDetail.as_view()),
    path('vendas/<int:pk>/add_item/', views_api.VendaAddItem.as_view()),
    path('vendas/<int:pk>/itens/<int:item_pk>/', views_api.VendaItemDetail.as_view()),
    path('vendas/<int:pk>/copiar/', views_api.VendaCopiar.as_view()),
    path('ultimo-preco-cliente-produto/', views_api.UltimoPrecoClienteProduto.as_view()),
    path('compras/', views_api.CompraListCreate.as_view()),
    path('compras/<int:pk>/', views_api.CompraDetail.as_view()),
    path('compras/<int:pk>/copiar/', views_api.CompraCopiar.as_view()),
    path('transacoes/', views_api.TransacaoListCreate.as_view()),
    path('logs/', views_api.LogList.as_view()),
    path('dividas-gerais/', views_api.DividaGeralListCreate.as_view()),
    path('dividas-gerais/<int:pk>/', views_api.DividaGeralDetail.as_view()),
    path('outros-a-receber/', views_api.OutrosAReceberListCreate.as_view()),
    path('outros-a-receber/<int:pk>/', views_api.OutrosAReceberDetail.as_view()),
    path('saidas/', views_api.SaidasListCreate.as_view()),
    path('estoque/', views_api.EstoqueList.as_view()),
    path('estoque/ajuste/', views_api.EstoqueAjuste.as_view()),
    path('estoque/ajuste-produto/', views_api.EstoqueAjusteProduto.as_view()),
    path('caixa/pagamento/', views_api.CaixaPagamento.as_view()),
    path('caixa/historico/', views_api.CaixaHistorico.as_view()),
    path('contas/<int:pk>/movimentos/', views_api.ContaMovimentos.as_view()),
    path('contas/<int:pk>/atualizar-saldo/', views_api.ContaAtualizarSaldo.as_view()),
    path('clientes/<int:pk>/detalhe/', views_api.ClienteDetalhe.as_view()),
    path('clientes/<int:pk>/precos-produtos/', views_api.ClientePrecosProdutos.as_view()),
    path('fornecedores/<int:pk>/materiais/', views_api.FornecedorMateriais.as_view()),
    path('fornecedores/<int:pk>/detalhe/', views_api.FornecedorDetalhe.as_view()),
    path('funcionarios/', views_api.FuncionarioListCreate.as_view()),
    path('funcionarios/<int:pk>/', views_api.FuncionarioDetail.as_view()),
    path('funcionarios/<int:pk>/horas-extras/', views_api.FuncionarioHoraExtraCreate.as_view()),
    path('funcionarios/<int:pk>/horas-extras/<int:he_pk>/', views_api.FuncionarioHoraExtraDelete.as_view()),
    path('funcionarios/<int:pk>/pagamentos/', views_api.FuncionarioPagamentoCreate.as_view()),
]
